name: On Pull Request

on:
  push:
    branches: [main]
  pull_request:
  schedule:
    - cron: "0 14 * * 1"

jobs:
  build_and_publish:
    name: Build and Publish the image
    uses: ./.github/workflows/build_and_publish_call.yaml
    secrets:
      DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
      DOCKER_HUB_ACCESS_TOKEN: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
